apiVersion: apps/v1
kind: Deployment
metadata:
  name: verademo-python-__CI_ENVIRONMENT_SLUG__
  labels:
    app: verademo-python
    ref: __CI_ENVIRONMENT_SLUG__
    track: stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verademo-python
      ref: __CI_ENVIRONMENT_SLUG__
  template:
    metadata:
      labels:
        app: verademo-python
        ref: __CI_ENVIRONMENT_SLUG__
        track: stable
    spec:
      containers:
      - name: app
        image: __IMAGE_TAG__
        imagePullPolicy: Always
        ports:
        - name: http
          protocol: TCP
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          timeoutSeconds: 2
